### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by argentum47** [JBakamovic/yavide#54]
```
Command "/usr/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ozg2u4uc/PyYAML/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-j0w6n66s-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ozg2u4uc/PyYAML/
```

What error is this. debian 8.

**Comment by JBakamovic** [comment]
Please attach the whole log. Something is not right with installing the Python dependencies.

**Comment by argentum47** [comment]
ok . I have to do it once again

**Comment by petermeng** [comment]
Have you solved this problem? I have the same one.

**Comment by JBakamovic** [comment]
It's Python dependency missing. I can't really tell more without more information. I haven't got Debian system running here.

Can you try running: `apt get install python-dev` and let me know if it works out for you? This is dependency which shall be installed by the `install.sh` script but something may have gone wrong.

**Comment by petermeng** [comment]
I have install python-dev and also tried to reinstall pip. But it still does not work.

**Comment by JBakamovic** [comment]
Can you try installing `python3-dev` package?

**Comment by petermeng** [comment]
Yes, I have install python3-dev.
Building dependency tree       
Reading state information... Done
python3-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

By the way, I tried to install "clang watchdog" manually. But it failed.

#pip2 install "clang watchdog"
Invalid requirement: 'clang watchdog'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 82, in __init__
    req = Requirement(req)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
InvalidRequirement: Invalid requirement, parse error at "'watchdog'"

**Comment by JBakamovic** [comment]
Correct syntax should be `pip2 install clang watchdog`. You have extra `"` there.

**Comment by petermeng** [comment]
OK, i will try it again.

**Comment by JBakamovic** [comment]
In any case I didn't see `clang`/`watchdog` failure in the log but only the one related to `libyaml-dev`. Can you please try running `apt-get install libyaml-dev`?

**Comment by petermeng** [comment]
I have installed libyaml-dev. By the way, is it possilbe that some of libs are very old?
# sudo apt-get install libyaml-dev
[sudo] password for peter: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libyaml-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.

**Comment by Claudius42** [comment]
As far as I understood your implementation works only with a vim version supporting python 2.x, correct?
Are there any plans to support vim compiled with '-python +python3'?

**Comment by JBakamovic** [comment]
Hm, having `python3` support should not break anything as long as there is `python2` support compiled in as well. However, using `python3` interpreter only would not work as project is `python 2.x` based. I am not sure I will be porting the code to new Python version. Probably not.

**Comment by Claudius42** [comment]
That's my problem, my installed vim (8.0.x) only supports python3 and not python 2.x. I use Ubuntu 14.04 LTS due to other requirements. I haven't found any pre-compiled binaries of vim supporting python 2.x and GUI for this target platform.
Which vim version do you use and did you get it? Can you provide any link or the parameters for the configure command to build vim from scratch in order to use your great setup?

**Comment by JBakamovic** [comment]
First of all, `Yavide` requires `gvim` so what you should be really looking is if your `gvim` has been compiled with `python2` support or not. This is a limitation mostly due to the `clientserver` feature which most distributions do not include in plain `vim`. There are numerous instructions on the web how to compile vim from the sources but I would advise to have a try with something from this [stackoverflow answer](https://stackoverflow.com/a/19601746). Read the comments as well.

**Comment by yoni206** [comment]
I have installed vim.gnome-py2, which has both python and clientserver support.
Is there a way to get Yavide work through vim and not gvim? Right now, the command `yavide` opens gvim.

**Comment by JBakamovic** [comment]
> Is there a way to get Yavide work through vim and not gvim? Right now, the command yavide opens gvim.

As I mentioned it above, `vim` is not distributed with `clientserver` support compiled in. If you find one elsewhere or compile `vim` yourself so it has that feature, with minor fix you should be able to run `yavide` without any problems. Fix is replacing `gvim` occurrence with `vim` [here](https://github.com/JBakamovic/yavide/blob/master/core/common/yavide_utils.py#L24) and [here](https://github.com/JBakamovic/yavide/blob/master/core/common/yavide_utils.py#L29).
