### ISSUE TITLE
Cannot find attribute 'clang.cindex.BaseEnumeration'

### ISSUE THREAD

**Issue by Morgoth890** [JBakamovic/yavide#74]
Hello,

I'm having trouble getting Yavide to run correctly.
I first had issues about watchdog and found i had to run "pip2.7 install watchdog" to get rid of that error, but now I'm having a similar issue on yavide that can't find clang.cindex.BaseEnumeration.
I'm not too good at Python, but there is nothing named BaseEnumeration in the clang/cindex.py file. Doing a grep on BaseEnumeration in the yavide folder only shows the clang_parser.py file that tries to access it but can't find it.
Running "pip2.7 install clang" also doesn't seem to fix the issue.

Here is the full error output:

```
Error detected while processing function Y_Env_Init[2]..Y_ServerStart:
line    8:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing function Y_Env_Init[2]..Y_ServerStart:
line    8:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing function Y_Env_Init[2]..Y_ServerStart:
line    8:
  File "/opt/yavide/core/server/yavide_server.py", line 8, in <module>
Press ENTER or type command to continue
Error detected while processing function Y_Env_Init[2]..Y_ServerStart:
line    8:
    from services.source_code_model_service import SourceCodeModel
Press ENTER or type command to continue
Error detected while processing function Y_Env_Init[2]..Y_ServerStart:
line    8:
  File "/opt/yavide/core/services/source_code_model_service.py", line 3, in <module>
Press ENTER or type command to continue
Error detected while processing function Y_Env_Init[2]..Y_ServerStart:
line    8:
    from services.parser.clang_parser import ClangParser
Press ENTER or type command to continue
Error detected while processing function Y_Env_Init[2]..Y_ServerStart:
line    8:
  File "/opt/yavide/core/services/parser/clang_parser.py", line 7, in <module>
Press ENTER or type command to continue
Error detected while processing function Y_Env_Init[2]..Y_ServerStart:
line    8:
    class ChildVisitResult(clang.cindex.BaseEnumeration):
Press ENTER or type command to continue
Error detected while processing function Y_Env_Init[2]..Y_ServerStart:
line    8:
AttributeError: 'module' object has no attribute 'BaseEnumeration'

```

Can anyone help me to fix this?

Thanks!

**Comment by JBakamovic** [comment]
Hi, sorry for a bit delayed reply.

`BaseEnumeration` should indeed be part of the `cindex.py` file. I am not sure why would you not have it there. Perhaps an not up to date version of `libclang` and/or its Python bindings? What system do you run? 

Try to update the libclang version **and** its Python bindings and let us know if it helped.

Cheers,
Adi

**Comment by Morgoth890** [comment]
Hello, no problem, thank you for replying.

I'm running on Gentoo.
I assumed that cindex.py came from yavide itself, or that it was trying to find it somewhere else. But reading that the file was supposed to define BaseEnumeration led me to compare the cindex.py from yavide/core/external/clang_complete/plugin/clang/cindex.py and the one installed by the clang-python package, and I found that they were not exactly the same. The one installed by clang-python defines BaseEnumeration as expected, but not the one from the yavide installation folder.

I tried to copy all the files from /usr/lib64/python2.7/site-packages/clang (the clang-python package files) to the yavide installation folder in yavide/core/external/clang_complete/plugin/clang/ and that fixed it! I'm now running yavide successfully!

Thanks a lot!

**Comment by JBakamovic** [comment]
Hm, the way you fixed the issue does not really correspond to the error message which you have attached above or perhaps I am not reading it well. `clang_complete` is an external Vim plugin which I chose to pack with `Yavide` to provide auto-completion functionality. But the error you described seems like it had something to do with your local installation of `clang-python`. I did not see any mention of `clang_complete` in the error report.

I would try to disable the plugin first and run everything once again and verify if you still get the error or not. You can disable the plugin by appending `~` to its directory name (i.e. `clang_complete` becomes `clang_complete~`).

Cheers,
Adi

**Comment by Morgoth890** [comment]
I just tried to disable clang_complete and I'm not getting any error, but the completion doesn't work anymore. Renaming the folder to its original name makes completion work again.

Yavide is then clearly reading cindex.py from the yavide installation folder, but the original cindex.py file (after installing yavide) didn't contain the BaseEnumeration definition.
Replacing the files from clang_complete in the yavide installation by the clang-python package files fixed the issue because cindex.py in that location defines BaseEnumeration.
It's like yavide fetches a clang_complete plugin version that is not compatible with itself.

**Comment by JBakamovic** [comment]
It could be that the wrong `cindex.py` is being imported. Haven't seen that kind of issue yet but we shall verify if this is really the case. Can you please do the following:

1. Disable `clang_complete` plugin
2. git checkout `concurrent_clang_indexer`
3. go to `core/server` directory
4. run `PYTHONPATH=../ python -v yavide_server.py`

In the given output please check where clang-related stuff is being imported from. You can paste the output here so I can have a look as well.

Thanks,
Adi

**Comment by Morgoth890** [comment]
Here's the output of the last command:

import _frozen_importlib # frozen
import imp # builtin
import sys # builtin
# installing zipimport hook
# installed zipimport hook
# /usr/lib/python-exec/python3.4/../../../lib64/python3.4/encodings/__pycache__/__init__.cpython-34.pyc matches /usr/lib/python-exec/python3.4/../../../lib64/python3.4/encodings/__init__.py
# code object from '/usr/lib/python-exec/python3.4/../../../lib64/python3.4/encodings/__pycache__/__init__.cpython-34.pyc'
# /usr/lib/python-exec/python3.4/../../../lib64/python3.4/__pycache__/codecs.cpython-34.pyc matches /usr/lib/python-exec/python3.4/../../../lib64/python3.4/codecs.py
# code object from '/usr/lib/python-exec/python3.4/../../../lib64/python3.4/__pycache__/codecs.cpython-34.pyc'
import 'codecs' # <_frozen_importlib.SourceFileLoader object at 0x7f9cb1e2e668>
# /usr/lib/python-exec/python3.4/../../../lib64/python3.4/encodings/__pycache__/aliases.cpython-34.pyc matches /usr/lib/python-exec/python3.4/../../../lib64/python3.4/encodings/aliases.py
# code object from '/usr/lib/python-exec/python3.4/../../../lib64/python3.4/encodings/__pycache__/aliases.cpython-34.pyc'
import 'encodings.aliases' # <_frozen_importlib.SourceFileLoader object at 0x7f9cb1dc6160>
import 'encodings' # <_frozen_importlib.SourceFileLoader object at 0x7f9cb1e2e208>
# /usr/lib/python-exec/python3.4/../../../lib64/python3.4/encodings/__pycache__/utf_8.cpython-34.pyc matches /usr/lib/python-exec/python3.4/../../../lib64/python3.4/encodings/utf_8.py
# code object from '/usr/lib/python-exec/python3.4/../../../lib64/python3.4/encodings/__pycache__/utf_8.cpython-34.pyc'
import 'encodings.utf_8' # <_frozen_importlib.SourceFileLoader object at 0x7f9cb1dcbe10>
# /usr/lib/python-exec/python3.4/../../../lib64/python3.4/encodings/__pycache__/latin_1.cpython-34.pyc matches /usr/lib/python-exec/python3.4/../../../lib64/python3.4/encodings/latin_1.py
# code object from '/usr/lib/python-exec/python3.4/../../../lib64/python3.4/encodings/__pycache__/latin_1.cpython-34.pyc'
import 'encodings.latin_1' # <_frozen_importlib.SourceFileLoader object at 0x7f9cb1dcf978>
# /usr/lib/python-exec/python3.4/../../../lib64/python3.4/__pycache__/io.cpython-34.pyc matches /usr/lib/python-exec/python3.4/../../../lib64/python3.4/io.py
# code object from '/usr/lib/python-exec/python3.4/../../../lib64/python3.4/__pycache__/io.cpython-34.pyc'
# /usr/lib/python-exec/python3.4/../../../lib64/python3.4/__pycache__/abc.cpython-34.pyc matches /usr/lib/python-exec/python3.4/../../../lib64/python3.4/abc.py
# code object from '/usr/lib/python-exec/python3.4/../../../lib64/python3.4/__pycache__/abc.cpython-34.pyc'
# /usr/lib/python-exec/python3.4/../../../lib64/python3.4/__pycache__/_weakrefset.cpython-34.pyc matches /usr/lib/python-exec/python3.4/../../../lib64/python3.4/_weakrefset.py
# code object from '/usr/lib/python-exec/python3.4/../../../lib64/python3.4/__pycache__/_weakrefset.cpython-34.pyc'
import '_weakrefset' # <_frozen_importlib.SourceFileLoader object at 0x7f9cb1dd46d8>
import 'abc' # <_frozen_importlib.SourceFileLoader object at 0x7f9cb1dcfe48>
import 'io' # <_frozen_importlib.SourceFileLoader object at 0x7f9cb1dcfba8>
# /usr/lib/python-exec/python3.4/../../../lib64/python3.4/__pycache__/_bootlocale.cpython-34.pyc matches /usr/lib/python-exec/python3.4/../../../lib64/python3.4/_bootlocale.py
# code object from '/usr/lib/python-exec/python3.4/../../../lib64/python3.4/__pycache__/_bootlocale.cpython-34.pyc'
import '_bootlocale' # <_frozen_importlib.SourceFileLoader object at 0x7f9cb1ddbda0>
Python 3.4.5 (default, Jul 30 2017, 21:42:03) 
[GCC 5.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
# /usr/lib/python-exec/python3.4/../../../lib64/python3.4/__pycache__/site.cpython-34.pyc matches /usr/lib/python-exec/python3.4/../../../lib64/python3.4/site.py
# code object from '/usr/lib/python-exec/python3.4/../../../lib64/python3.4/__pycache__/site.cpython-34.pyc'
# /usr/lib/python-exec/python3.4/../../../lib64/python3.4/__pycache__/os.cpython-34.pyc matches /usr/lib/python-exec/python3.4/../../../lib64/python3.4/os.py
# code object from '/usr/lib/python-exec/python3.4/../../../lib64/python3.4/__pycache__/os.cpython-34.pyc'
# /usr/lib/python-exec/python3.4/../../../lib64/python3.4/__pycache__/stat.cpython-34.pyc matches /usr/lib/python-exec/python3.4/../../../lib64/python3.4/stat.py
# code object from '/usr/lib/python-exec/python3.4/../../../lib64/python3.4/__pycache__/stat.cpython-34.pyc'
import 'stat' # <_frozen_importlib.SourceFileLoader object at 0x7f9cb1dfd978>
# /usr/lib/python-exec/python3.4/../../../lib64/python3.4/__pycache__/posixpath.cpython-34.pyc matches /usr/lib/python-exec/python3.4/../../../lib64/python3.4/posixpath.py
# code object from '/usr/lib/python-exec/python3.4/../../../lib64/python3.4/__pycache__/posixpath.cpython-34.pyc'
# /usr/lib/python-exec/python3.4/../../../lib64/python3.4/__pycache__/genericpath.cpython-34.pyc matches /usr/lib/python-exec/python3.4/../../../lib64/python3.4/genericpath.py
# code object from '/usr/lib/python-exec/python3.4/../../../lib64/python3.4/__pycache__/genericpath.cpython-34.pyc'
import 'genericpath' # <_frozen_importlib.SourceFileLoader object at 0x7f9cb1d862b0>
import 'posixpath' # <_frozen_importlib.SourceFileLoader object at 0x7f9cb1dfdcf8>
# /usr/lib/python-exec/python3.4/../../../lib64/python3.4/__pycache__/_collections_abc.cpython-34.pyc matches /usr/lib/python-exec/python3.4/../../../lib64/python3.4/_collections_abc.py
# code object from '/usr/lib/python-exec/python3.4/../../../lib64/python3.4/__pycache__/_collections_abc.cpython-34.pyc'
import '_collections_abc' # <_frozen_importlib.SourceFileLoader object at 0x7f9cb1d861d0>
import 'os' # <_frozen_importlib.SourceFileLoader object at 0x7f9cb1def208>
# /usr/lib/python-exec/python3.4/../../../lib64/python3.4/__pycache__/_sitebuiltins.cpython-34.pyc matches /usr/lib/python-exec/python3.4/../../../lib64/python3.4/_sitebuiltins.py
# code object from '/usr/lib/python-exec/python3.4/../../../lib64/python3.4/__pycache__/_sitebuiltins.cpython-34.pyc'
import '_sitebuiltins' # <_frozen_importlib.SourceFileLoader object at 0x7f9cb1def550>
# /usr/lib64/python3.4/__pycache__/sysconfig.cpython-34.pyc matches /usr/lib64/python3.4/sysconfig.py
# code object from '/usr/lib64/python3.4/__pycache__/sysconfig.cpython-34.pyc'
import 'sysconfig' # <_frozen_importlib.SourceFileLoader object at 0x7f9cb1db3da0>
# /usr/lib64/python3.4/__pycache__/_sysconfigdata.cpython-34.pyc matches /usr/lib64/python3.4/_sysconfigdata.py
# code object from '/usr/lib64/python3.4/__pycache__/_sysconfigdata.cpython-34.pyc'
import '_sysconfigdata' # <_frozen_importlib.SourceFileLoader object at 0x7f9cb1dbf748>
# /usr/lib64/python3.4/__pycache__/types.cpython-34.pyc matches /usr/lib64/python3.4/types.py
# code object from '/usr/lib64/python3.4/__pycache__/types.cpython-34.pyc'
import 'types' # <_frozen_importlib.SourceFileLoader object at 0x7f9cb1d19b00>
import 'site' # <_frozen_importlib.SourceFileLoader object at 0x7f9cb1de5d30>
Traceback (most recent call last):
  File "yavide_server.py", line 1, in <module>
    import copy_reg
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'copy_reg'
# clear builtins._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.last_type
# clear sys.last_value
# clear sys.last_traceback
# clear sys.path_hooks
# clear sys.path_importer_cache
# clear sys.meta_path
# clear sys.__interactivehook__
# clear sys.flags
# clear sys.float_info
# restore sys.stdin
# restore sys.stdout
# restore sys.stderr
# cleanup[2] removing encodings.utf_8
# cleanup[2] removing _stat
# cleanup[2] removing io
# destroy io
# cleanup[2] removing _locale
# cleanup[2] removing builtins
# cleanup[2] removing _sitebuiltins
# cleanup[2] removing stat
# cleanup[2] removing site
# destroy site
# cleanup[2] removing os
# cleanup[2] removing posix
# cleanup[2] removing _weakrefset
# destroy _weakrefset
# cleanup[2] removing errno
# cleanup[2] removing ndg
# destroy ndg
# cleanup[2] removing _frozen_importlib
# cleanup[2] removing _bootlocale
# destroy _bootlocale
# cleanup[2] removing signal
# cleanup[2] removing _weakref
# cleanup[2] removing _thread
# cleanup[2] removing encodings.aliases
# cleanup[2] removing encodings.latin_1
# cleanup[2] removing _warnings
# cleanup[2] removing _imp
# cleanup[2] removing _codecs
# cleanup[2] removing os.path
# cleanup[2] removing zipimport
# cleanup[2] removing posixpath
# cleanup[2] removing marshal
# cleanup[2] removing encodings
# destroy encodings
# cleanup[2] removing sys
# cleanup[2] removing _sysconfigdata
# destroy _sysconfigdata
# cleanup[2] removing types
# destroy types
# cleanup[2] removing codecs
# cleanup[2] removing google
# destroy google
# cleanup[2] removing _io
# cleanup[2] removing genericpath
# cleanup[2] removing sysconfig
# destroy sysconfig
# cleanup[2] removing __main__
# destroy __main__
# cleanup[2] removing abc
# destroy abc
# cleanup[2] removing _collections_abc
# destroy _collections_abc
# destroy zipimport
# destroy signal
# destroy _locale
# destroy _sitebuiltins
# destroy posixpath
# destroy errno
# destroy _stat
# destroy genericpath
# destroy stat
# destroy os
# cleanup[3] wiping encodings.utf_8
# cleanup[3] wiping posix
# cleanup[3] wiping _frozen_importlib
# destroy posix
# cleanup[3] wiping _weakref
# destroy _weakref
# cleanup[3] wiping _thread
# destroy _thread
# cleanup[3] wiping encodings.aliases
# cleanup[3] wiping encodings.latin_1
# cleanup[3] wiping _warnings
# destroy _warnings
# cleanup[3] wiping _imp
# destroy _imp
# cleanup[3] wiping _codecs
# cleanup[3] wiping marshal
# destroy marshal
# cleanup[3] wiping codecs
# cleanup[3] wiping _io
# destroy io
# cleanup[3] wiping sys
# cleanup[3] wiping builtins
# destroy _frozen_importlib

**Comment by JBakamovic** [comment]
Hm, there doesn't seem to be any mention of `libclang` related imports (i.e. `cindex.py`). I believe this is because your default Python interpreter is set to `Python3`. Both `Yavide` and `libclang` bindings support `Python2` only. There is no support for `Python3` as of now and therefore there is no such package for `libclang` bindings.

In order to run `Yavide` properly you should be using `Python2` interpreter. I am not sure if `Python3` is picked up due to it being a default system configuration and/or (g)vim is actually compiled with `Python3` support only. Can you please c/p the output of following commands:
* python --version
* gvim --version

**Comment by Morgoth890** [comment]
Indeed, my default python is python3.

$ python --version
Python 3.4.5
$ gvim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 30 2017 20:08:08)
Included patches: 1-386
Modified by Gentoo-8.0.0386
Compiled by nico@gentoo
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    -netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python/dyn      +vreplace
-cscope          +lispindent      +python3/dyn     +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  -lua             +rightleft       +writebackup
+diff            +menu            -ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xpm
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "/etc/vim/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/vim/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: x86_64-pc-linux-gnu-gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/freetype2    -O2 -pipe -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: x86_64-pc-linux-gnu-gcc   -Wl,-E  -Wl,-O1 -L/usr/local/lib -Wl,--as-needed -o gvim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype  -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses -lnsl    -lacl -lattr -ldl   -Wl,-E -Wl,-O1 -Wl,--as-needed  -L/usr/lib64/perl5/5.24.1/x86_64-linux/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc

**Comment by JBakamovic** [comment]
Your `gvim` is compiled with support for both Python2 and Python3 which, according to the [official documentation](http://vimdoc.sourceforge.net/htmldoc/if_pyth.html#python3), can be somewhat problematic.

Do you have any easy way on Gentoo to run `gvim` compiled with Python2 support only? Alternative would be to set your system's default Python interpreter to Python2 but I am not sure if that would break anything else for you ... so I would be more in favor of the first option.

**Comment by Zitara** [comment]
On Ubuntu, python bindings to Clang with the package:
`sudo apt-get install python-clang-6.0`, should do the trick.
Based on [stackoverflow](https://stackoverflow.com/questions/26111885/clang-ctags-error-importerror-no-module-named-clang-cindex).
